[opensearch]
os-a ansible_host=3.108.226.172 ansible_user=ubuntu
os-b ansible_host=13.203.95.104 ansible_user=ec2-user
os-c ansible_host=52.66.224.141 ansible_user=ec2-user

[opensearch:vars]
ansible_ssh_private_key_file=./Oskey.pem
ansible_ssh_common_args='-o StrictHostKeyChecking=no'
