---
- name: Wait for cluster green
  uri:
    url: "http://localhost:9200/_cluster/health"
    method: GET
  register: health
  until: health.json.status in ["green", "yellow"]
  retries: 10
  delay: 10

# ===========================
# Create Snapshot Repository
# ===========================

- name: Create snapshot repository
  uri:
    url: "http://localhost:9200/_snapshot/{{ opensearch_backup_repo }}"
    method: PUT
    user: "{{ opensearch_backup_username | default(opensearch_admin_username) }}"
    password: "{{ opensearch_backup_password | default(opensearch_admin_password) }}"
    force_basic_auth: true
    validate_certs: false
    body_format: json
    body:
      type: s3
      settings:
        bucket: "{{ opensearch_backup_bucket }}"
        endpoint: "{{ minio_endpoint }}"
        protocol: "{{ minio_protocol }}"
        region: "us-east-1"
        path_style_access: true
        access_key: "{{ minio_access_key }}"
        secret_key: "{{ minio_secret_key }}"
    status_code: [200, 201]

- name: Wait before snapshot (cluster stable)
  pause:
    seconds: 30

# ===========================
# Create Snapshot (BACKUP)
# ===========================

- name: Create snapshot
  uri:
    url: "http://localhost:9200/_snapshot/{{ opensearch_backup_repo }}/{{ opensearch_backup_name }}"
    method: PUT
    user: "{{ opensearch_admin_username }}"
    password: "{{ opensearch_admin_password }}"
    force_basic_auth: true
    validate_certs: false
    body_format: json
    body:
      indices: "*"
      ignore_unavailable: true
      include_global_state: false
    status_code: [200, 201]
