---
- name: Determine protocol
  ansible.builtin.set_fact:
    opensearch_protocol: "{{ 'https' if opensearch_use_tls else 'http' }}"

- name: Wait for OpenSearch port to be open
  ansible.builtin.wait_for:
    port: "{{ opensearch_http_port }}"
    host: "127.0.0.1"
    state: started
    timeout: 300

- name: Wait for OpenSearch HTTP health check
  ansible.builtin.uri:
    url: "{{ opensearch_protocol }}://127.0.0.1:{{ opensearch_http_port }}/_cluster/health"
    method: GET
    # Always provide auth if we have it, as the security plugin might be active
    user: "{{ opensearch_admin_username | default('admin') }}"
    password: "{{ opensearch_admin_password }}"
    force_basic_auth: yes
    validate_certs: no
    status_code: 200
    timeout: 5
  register: cluster_health
  until: cluster_health.status == 200
  retries: 100
  delay: 2

- name: Apply Default Index Template (Shards/Replicas)
  ansible.builtin.uri:
    url: "{{ opensearch_protocol }}://{{ opensearch_network_host }}:{{ opensearch_http_port }}/_index_template/default_template"
    method: PUT
    user: "{{ opensearch_admin_username if opensearch_use_tls else omit }}"
    password: "{{ opensearch_admin_password if opensearch_use_tls else omit }}"
    force_basic_auth: "{{ opensearch_use_tls }}"
    body: "{{ lookup('template', 'default_template.json.j2') }}"
    body_format: json
    validate_certs: no
    status_code: [200, 201]
  # Only run this on one node (e.g. the first master)
  when: inventory_hostname == (opensearch_initial_master_nodes | first | default(inventory_hostname))

