- name: Configuring Internal User file
  template:
    src: user.yaml
    dest: "{{ Opensearch_Dir }}/plugins/opensearch-security/securityconfig/internal_users.yml"
    mode: 0644
  become: true
 
- name: Seeting admin password
  shell: >
    sed -i '/hash: / s,{{ admin_password }},'$(bash {{ Opensearch_Dir }}/plugins/opensearch-security/tools/hash.sh -p {{ admin_password }} | tail -1)','
    {{ Opensearch_Dir }}/plugins/opensearch-security/securityconfig/internal_users.yml
  become: true

- name: Seeting kibana password
  shell: >
    sed -i '/hash: / s,{{ kibanaserver_password }},'$(bash {{ Opensearch_Dir }}/plugins/opensearch-security/tools/hash.sh -p {{ kibanaserver_password }} | tail -1)','
    {{ Opensearch_Dir }}/plugins/opensearch-security/securityconfig/internal_users.yml
  become: true

- name: Running all handlers for opensearch nodes
  meta: flush_handlers

