---
- name: Restart OpenSearch
  ansible.builtin.service:
    name: opensearch
    state: restarted

- name: Restart OpenSearch Dashboards
  ansible.builtin.service:
    name: opensearch-dashboards
    state: restarted
