---
- name: Install dependencies for Debian/Ubuntu
  ansible.builtin.apt:
    name:
      - curl
      - gnupg
      - lsb-release
      - ca-certificates
    state: present
    update_cache: yes

- name: Import OpenSearch GPG Key
  ansible.builtin.apt_key:
    url: https://artifacts.opensearch.org/publickeys/opensearch.pgp
    state: present

- name: Add OpenSearch repository
  ansible.builtin.apt_repository:
    repo: "deb https://artifacts.opensearch.org/releases/bundle/opensearch/2.x/apt stable main"
    state: present
    filename: opensearch-2.x

- name: Add OpenSearch Dashboards repository
  ansible.builtin.apt_repository:
    repo: "deb https://artifacts.opensearch.org/releases/bundle/opensearch-dashboards/2.x/apt stable main"
    state: present
    filename: opensearch-dashboards-2.x
  when: opensearch_install_dashboard
